from .arrays import (
    plot_array,
    plot_histogram,
    plot_scatter,
    plot_multiple_arrays,
    plot_array_with_mean,
    plot_running_mean,
    plot_boxplot,
    plot_density,
    plot_cdf,
    plot_error_bars,
    plot_rolling_std,
    plot_min_max_band,
    plot_autocorrelation,
    plot_quantiles,
    plot_scatter_with_fit,
    plot_dual_axis,
)

from .matrices import (
    plot_matrix_heatmap,
    plot_confusion_matrix,
    plot_matrix_surface,
    plot_matrix_contour,
    plot_matrix_with_values,
    plot_correlation_matrix,
    plot_similarity_matrix,
    plot_matrix_histogram,
    plot_masked_heatmap,
    plot_confusion_matrix_normalized,
    plot_attention_map,
    plot_matrix_sparsity,
)

from .training import (
    plot_training_history,
    plot_metric,
    plot_train_vs_val,
    plot_learning_rate,
    plot_metric_with_best,
    plot_metrics_grid,
    plot_confidence_band,
    plot_early_stopping,
    plot_epoch_time,
)

from .three_d import plot_3d_scatter, plot_3d_surface
from .report import figures_to_html_img_tags, save_figures_pdf

__all__ = [
    "plot_array",
    "plot_histogram",
    "plot_scatter",
    "plot_multiple_arrays",
    "plot_array_with_mean",
    "plot_running_mean",
    "plot_boxplot",
    "plot_density",
    "plot_cdf",
    "plot_error_bars",
    "plot_rolling_std",
    "plot_min_max_band",
    "plot_autocorrelation",
    "plot_quantiles",
    "plot_scatter_with_fit",
    "plot_dual_axis",
    "plot_matrix_heatmap",
    "plot_confusion_matrix",
    "plot_matrix_surface",
    "plot_matrix_contour",
    "plot_matrix_with_values",
    "plot_correlation_matrix",
    "plot_similarity_matrix",
    "plot_matrix_histogram",
    "plot_masked_heatmap",
    "plot_confusion_matrix_normalized",
    "plot_attention_map",
    "plot_matrix_sparsity",
    "plot_training_history",
    "plot_metric",
    "plot_train_vs_val",
    "plot_learning_rate",
    "plot_metric_with_best",
    "plot_metrics_grid",
    "plot_confidence_band",
    "plot_early_stopping",
    "plot_epoch_time",
    "plot_3d_scatter",
    "plot_3d_surface",
    "save_figures_pdf",
    "figures_to_html_img_tags",
]
